#!/bin/bash

rm -rf dist && \
  yarn build:site && \
  cd dist && \
  git init && \
  git remote add origin git@github.com:mjmlio/mjml-app.git && \
  git add . && \
  git commit -m 'deploy' && \
  git push -f origin master:gh-pages && \
  printf '\n> everything has been deployed\n'
